# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=8, verbose_name='性别')),
                ('birthday', models.DateField(default='1990-1-1', verbose_name='生日')),
                ('avatar', models.ImageField(max_length=256, upload_to='', verbose_name='头像')),
                ('location', models.CharField(choices=[('上海', '上海'), ('北京', '北京'), ('广东', '广东'), ('南京', '南京'), ('重庆', '重庆'), ('西安', '西安'), ('武汉', '武汉'), ('长沙', '长沙')], default='北京', max_length=16, verbose_name='居住地')),
            ],
        ),
    ]
