# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='匹配的性别')),
                ('location', models.CharField(choices=[('上海', '上海'), ('北京', '北京'), ('广东', '广东'), ('南京', '南京'), ('重庆', '重庆'), ('西安', '西安'), ('武汉', '武汉'), ('长沙', '长沙')], max_length=16, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最⼩查找范围')),
                ('max_distance', models.IntegerField(default=30, verbose_name='最⼤查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最⼩交友年年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让为匹配的⼈人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
        ),
    ]
